# Generated by Django 3.2.9 on 2021-12-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleofmedicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmedicine',
            name='sales',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saleofmedicines.sales'),
        ),
    ]
